server:
  port: 10091
spring:
  application:
    name: springboot-pwd-encryption-using-jasypt
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    password: ENC(UmrR2+gpNNDzf5dr/HWWyDE4Ak1SfDbW)
    url: jdbc:postgresql://localhost:5432/postgres
    username: ENC(VDyBwp9lXgNt8OVKfDnK6+7EhDPvH8y6)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html